apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "backstage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backstage.selectorLabels" . | nindent 8 }}
        {{- include "common.labels" . | nindent 8 }}
      annotations:
        {{- include "common.annotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "backstage.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: backstage
          image: "{{ .Values.image.uri }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7007
              protocol: TCP
          env:
            - name: APP_BASE_URL
              value: "https://{{ .Values.domain }}"
            - name: BACKEND_BASE_URL
              value: "https://{{ .Values.domain }}"
            - name: CORS_ORIGIN
              value: "https://{{ .Values.domain }}"
            - name: ORGANIZATION_NAME
              value: "{{ .Values.organization }}"
            - name: AUTH_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.github.secretName }}
                  key: client_id
            - name: AUTH_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.github.secretName }}
                  key: client_secret
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /.backstage/health/v1/liveness
              port: http
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /.backstage/health/v1/readiness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: backstage-secrets
              mountPath: /app/secrets
              readOnly: true
            - name: backstage-config
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: backstage-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "backstage.fullname" . }}-secretprovider
        - name: backstage-config
          configMap:
            name: {{ include "backstage.fullname" . }}-config
