apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.auth.github.secretName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.auth.github.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: {{ .Values.auth.github.awsSecretName }}
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: {{ .Values.auth.github.awsSecretName }}
        property: client_secret
