apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "backstage.fullname" . }}-secretprovider
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.database.secretName }}"
        objectType: "secretsmanager"
        jmesPath:
        - path: "username"
          objectAlias: "'db-username'"
        - path: "password"
          objectAlias: "'db-password'"
        - path: "host"
          objectAlias: "'db-host'"
      - objectName: "{{ .Values.auth.github.secretName }}"
        objectType: "secretsmanager"
        jmesPath:
        - path: "client_id"
          objectAlias: "'github-client-id'"
        - path: "client_secret"
          objectAlias: "'github-client-secret'"
  secretObjects:
    - secretName: {{ .Values.database.secretName }}
      type: Opaque
      data:
        - key: username
          objectName: "'db-username'"
        - key: password
          objectName: "'db-password'"
        - key: host
          objectName: "'db-host'"
    - secretName: {{ .Values.auth.github.secretName }}
      type: Opaque
      data:
        - key: client_id
          objectName: "'github-client-id'"
        - key: client_secret
          objectName: "'github-client-secret'"
